### ISSUE TITLE
Não atualiza ao excluir produtos no carrinho

### ISSUE THREAD

**Issue by web1989** [opencartbrasil/todas-url-amigaveis#2]
Obrigado por essa extensão
Queria tirar uma dúvida.
Quando ativo ele, e a url do carrinho fica assim meudominio.com/carrinho ao tentar excluir um produto, a página não atualiza, porém se eu dar f5 o produto sai do carrinho, porém, quando esta com a url normal do opencart index.php?route=checkout/cart ele atualiza normal.
Pode ver isso pra mim?

Grato

**Comment by v5mvidal** [comment]
Olá.

Assumindo que seu tema utiliza a mesma base do tema padrão do OpenCart, você precisa fazer uma modificação no arquivo catalog/view/javascript/common.js
- No arquivo common.js, localize as linhas:
  location = 'index.php?route=checkout/cart';
- E substitua por:
  location = 'carrinho';
- Localize as linhas:
  if (getURLVar('route') == 'checkout/cart' || getURLVar('route') == 'checkout/checkout') {
- E substitua por:
  var getURlRewrite = $(location).attr('href').split('/').pop();
  if (getURlRewrite == 'carrinho' || getURlRewrite == 'finalizar-pedido') {

Salve as alterações no arquivo, limpe o cache do seu navegador e faça um teste. :)

**Comment by web1989** [comment]
Perfeito @ManoelVidal  
Obrigado
