### ISSUE TITLE
Adaptar na 2.2.0.0

### ISSUE THREAD

**Issue by cesarhenrique** [opencartbrasil/todas-url-amigaveis#3]
Como a estrutura mudou, então basta modificar as seguintes linhas para funcionar na versão 2.2.0.0:
Linha 8 de `catalog/controller/common/seo_url.php` para `catalog/controller/startup/seo_url.php`
Linha 10 de `ControllerCommonSeoUrl extends Controller` para `ControllerStartupSeoUrl extends Controller`

**Comment by ManoelVidal** [comment]
#e78f6b18a7264a030c08d1490898b85fca3c19af

**Comment by v5mvidal** [comment]
Atualizado :+1:
